# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather_App
	pod 'RxSwift', '6.7.0'
	pod 'RxCocoa', '6.7.0'
	pod 'Alamofire', '~> 5.9.1'
	pod 'ObjectMapper', '~> 4.4.2'
	pod 'SDWebImage', '~> 5.0'
	pod 'Reusable', '4.1.2'
	pod 'SwiftLint', '0.54.0'
    	pod 'Then', '3.0.0'
	pod 'Localize-Swift', '~> 3.2'
	pod 'SwiftGen', '6.6.3'

  target 'Weather_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Weather_AppUITests' do
    # Pods for testing
  end

end
